/**
 * Sentinel Fraud Detection System — Barrel Export
 */
export * from "./fraudDetection";
export {
  // Re-export everything except AlertSeverity (already exported by fraudDetection)
  type DocumentType,
  type VerificationStageType,
  type DocumentStatus,
  type VehicleType as KYCVehicleType,
  type LicenseCategory,
  type InsuranceCoverageType,
  type CNIEData,
  type CNIEValidation,
  type LicenseData,
  type LicenseValidation,
  type InsuranceData,
  type InsuranceValidation,
  type AutoEntrepreneurData,
  type AutoEntrepreneurValidation,
  type VehicleInspectionData,
  type VehicleInspectionValidation,
  type MedicalCertificateData,
  type MedicalCertificateValidation,
  type CriminalRecord,
  type CasierJudiciaireData,
  type CasierJudiciaireValidation,
  type SelfieVerificationData,
  type SelfieVerificationValidation,
  type VehicleRegistrationData,
  type VehicleRegistrationValidation,
  type DriverDocument,
  type KYCProgress,
  type ExpiryAlert,
  type VerificationStage,
  type ReVerificationSchedule,
  type ReVerificationTask,
  type DriverProfile,
  type KYCResult,
  type FleetKYCStats,
  type ComplianceResult,
  KYC_CONSTANTS,
  getRequiredDocuments,
  validateDocument,
  calculateKYCProgress,
  checkDocumentExpiry,
  determineVerificationStage,
  scheduleReVerification,
  isDriverEligible,
  validateCNIE,
  validateDrivingLicense,
  validateInsurance,
  validateAutoEntrepreneur,
  validateVehicleInspection,
  validateMedicalCertificate,
  validateCasierJudiciaire,
  validateSelfieWithCNIE,
  runKYCAssessment,
  generateReVerificationTasks,
  batchKYCAssessment,
  getFleetKYCStats,
  checkDocumentCompliance,
  formatDocumentTypeName,
} from "./driverVerification";
